---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: products
spec:
  interval: 1m
  chart:
    spec:
      chart: ./module/helm-application
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  releaseName: products
  values:
    image: nginx:latest
    port: 8080